### PR TITLE
Addresses #12, #13

### PR DESCRIPTION
**Pull request by dxdc**
@mjcumming I've made a number of updates here by reviewing the ISY firmware.

### Updates

- Used ZWave property mapping pulled from ISY firmware
 > Updated existing filenames to mirror this structure
- Update door lock properties to add missing properties (alarm, lock status)
 > Also, added `alarmcode` property here in case the integer value is preferable
- Added missing paddle events for Insteon devices. I am not sure how to use `FDDOWN` and `FDUP` per looking at the firmware, so left those commented for now.
- Added support for barrier, binary, and notification sensors. I'm less confident about the binary/notification sensors, but the barrier appears to be consistent with ISY firmware.

### Suggestions
- It may be better to add a parser for the [`uom` property](https://wiki.universal-devices.com/index.php?title=ISY_Developers:API:V5:Appendix:Units_of_Measure) instead of trying to repeat this logic in multiple places
- In `device_power.py`, this line has no default set. I would have changed it, but not sure what to change it to.
```py
   self.add_property("power")
```
- In the PIP package, I see a number of `.py` files that appear in the `isy994/items/devices` folder. Are these left over from an old deployment? I don't see them in the repo.

### Other
- I need to look at ISY-homie and see what updates need to be made there to add support for these sensors

### CODE REVIEW

**Comment by dxdc** [comment]
I also reverted cc70275f5405cd77a01355cb59aadb5d1af6a5cc because it is not as accurate for the barrier device type.

**Review by mjcumming — APPROVED** [review]

**Comment by mjcumming** [comment]
Made a few fixes.

Notes:

1. Not sure what power should be defaulted to
2. Not sure what what you mean with the uofm for parsing?
3. devices/items should only contain 3 files. Not sure why there are other files in there from package

**Comment by dxdc** [comment]
> Not sure what power should be defaulted to

OK, I wasn't sure either. I don't have any such devices.

> Not sure what what you mean with the uofm for parsing?

Have a look at this link: https://wiki.universal-devices.com/index.php?title=ISY_Developers:API:V5:Appendix:Units_of_Measure

This is also detailed out in the firmware (see attached). It would be ideal to build an XML parser for this to dynamically generate a Python class directly from the firmware.

[udiuom.xsd.zip](https://github.com/mjcumming/ISY994v5/files/4542277/udiuom.xsd.zip)

This HomeAssistant library already appears to be fairly close, but didn't compare it with the spec to confirm. Some fairly significant refactoring would be needed to use this though. But, it does seem that ISY reports `uom` (unit of measure)` along with its XML data so presumably this can be extracted.

https://github.com/shbatm/home-assistant/blob/isy994-variable-sensors/homeassistant/components/isy994/sensor.py

> devices/items should only contain 3 files. Not sure why there are other files in there from package

I'm not sure either. If I install it via:

```
pip3 install ISY994-Homie4-Bridge --user 
```

This is what I see inside isy994/items/devices. Not sure if it's a reference to something in the installation procedure for ISY-Homie-Bridge?

```
drwxr-xr-x 3 pi pi 4096 Apr 27 17:44 common/
-rw-r--r-- 1 pi pi  614 Apr 27 17:44 device_base.py
-rw-r--r-- 1 pi pi  280 Apr 27 17:44 device_contact.py
-rw-r--r-- 1 pi pi 2786 Apr 27 17:44 device_container.py
-rw-r--r-- 1 pi pi  330 Apr 27 17:44 device_dimmer.py
-rw-r--r-- 1 pi pi  386 Apr 27 17:44 device_fan.py
-rw-r--r-- 1 pi pi 3257 Apr 27 17:44 device_info.py
-rw-r--r-- 1 pi pi  472 Apr 27 17:44 device_lock.py
-rw-r--r-- 1 pi pi  266 Apr 27 17:44 device_power.py
-rw-r--r-- 1 pi pi  413 Apr 27 17:44 device_speed_controller.py
-rw-r--r-- 1 pi pi  357 Apr 27 17:44 device_switch.py
-rw-r--r-- 1 pi pi  625 Apr 27 17:44 device_thermostat.py
-rw-r--r-- 1 pi pi    0 Apr 27 17:44 __init__.py
drwxr-xr-x 3 pi pi 4096 Apr 27 17:44 insteon/
drwxr-xr-x 2 pi pi 4096 Apr 27 17:44 __pycache__/
drwxr-xr-x 3 pi pi 4096 Apr 27 17:44 zwave/
```

**Comment by dxdc** [comment]
Btw, thanks for making this awesome interface with ISY! Also, I didn't see any additional fixes?

**Comment by mjcumming** [comment]
Agree, the UOM, would be useful for devices beyond simple lights and switches. Worth looking at. I am using all Insteon and the only non switch/dimmer device I have is a thermostat. 

The HA library is based of PyISY which I looked at but decided to start over with. The code base just seems very disorganized. But there is useful information in those modules. 

Aren't the files listed in the common directory?

One main goal of building this library was to remove any dependency on the underlying technology so where possible to have a common switch device, that would work regardless if its Insteon, Z-Wave, etc.

**Comment by dxdc** [comment]
> The HA library is based of PyISY which I looked at but decided to start over with. The code base just seems very disorganized. But there is useful information in those modules.

Agreed

> Aren't the files listed in the common directory?

Yes, also there. That was confusing.

> One main goal of building this library was to remove any dependency on the underlying technology so where possible to have a common switch device, that would work regardless if its Insteon, Z-Wave, etc.

Yes, I like your philosophy! Also, I discovered a nice idea. You can use your library to detect multiple DON/DOF manual presses of a switch. So, in this way, you can set up interesting design patterns... for ex. 3 clicks up and 1 click down --> turn off all lights in the house.

**Comment by mjcumming** [comment]
Must be a benefit of ZWave - I find using paddle sequences from Insteon to not be very reliable. About the only one that works is a double click. If you the new zwave devices working in this package then we can look at changes to the bridge and creating a couple of new homie devices.

**Comment by dxdc** [comment]
@mjcumming I too have Insteon light switches. I can see the DOF/DON commands coming through on MQTT. I am only using this in the context of the Homie-Bridge package (pushed a PR there as well) but will try to install directly from the repo and see if my changes are working there also.

I'm also hopeful that the DON3, DON4, etc. commands may be recognized. A "double-click" (e.g., DON2) isn't used because ISY/Insteon considers this a fast on/off.

**Pull request merged**
